### ISSUE TITLE
Documentation broken

### ISSUE THREAD

**Issue by andrenarchy** [ChuckJonas/ts-force#101]
The documentation link in the README (https://app.gitbook.com/@cjonas/s/ts-force) doesn't seem to work anymore.

**Comment by ChuckJonas** [comment]
Thank you for notifying me... I tried to upgrade to the Open Source licenses for gitbook and it seems they messed something up.  

You can find the plain markdown version of the docs here https://github.com/ChuckJonas/ts-force/tree/master/docs

**Comment by ChuckJonas** [comment]
NVM, the link has just changed because it's an org now.  Readme is updated. Thanks again
