### ISSUE TITLE
Upgrade to axios 0.24.0?

### ISSUE THREAD

**Issue by jesse23** [ChuckJonas/ts-force#117]
Is it possible to upgrate to axios 0.24.0? There is a compatibility issue between 0.21.4 and 0.24.0...

**Comment by ChuckJonas** [comment]
updated in the `3.1.0-beta.1` version.  Let me know if you have any issues.  

Since we expose the underlying axois objects, I think this might be considered a breaking change...

**Comment by jesse23** [comment]
Definitely....

Also just FYI I tried force convert old axios to the new (by ts 'as') in my project and it works fine...
