### ISSUE TITLE
Enable Username/Password oAuth Flow for Server-side applications

### ISSUE THREAD

**Issue by DServy** [ChuckJonas/ts-force#13]
For usings TS-Force with node, enable server side authentication

Note: Will probably need to have both a sync and async method for doing this

**Comment by ChuckJonas** [comment]
Love to see this happen.  The authentication/configuration is the last missing piece that may result in large scale breaking changes.  

Once that's don't I feel it will be stable enough to include in projects without fear that you'll have to do major refactors
