### ISSUE TITLE
Where clause on date fields

### ISSUE THREAD

**Issue by robbiefryers** [ChuckJonas/ts-force#158]
Querying on [dateTime](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm) fields works really well. For example:

```
const query = buildQuery(SFProduct, f => ({
    select: [f.select('createdAt')],
    where: [{ field: f.select('createdAt'), op: '<=', val: new Date() }],
    limit: 1
}));

// generates the following:
// SELECT CreatedDate FROM Product WHERE CreatedDate <= 2024-01-01T00:00:00.000Z LIMIT 1
```

However if i want to query on a date field, the generated query cause an error to be thrown

```
const query = buildQuery(SFProduct, f => ({
    select: [f.select('discontinuedOn')],
    where: [{ field: f.select('discontinuedOn'), op: '<=', val: '2024-05-01' }],
    limit: 1
}));

// generates the following:
// SELECT DiscontinuedDate FROM Product WHERE DiscontinuedDate <= '2024-05-01' LIMIT 1
```

A valid query must not include the quotes around the date.

**Comment by ChuckJonas** [comment]
@robbiefryers ya, by default ts-force wraps strings in `'`.  But you can use a custom formatter to override this:

```
{
     field: fields.select('createdDate'),
     op: '<',
     val: '2020-01-01',
     formatter: (it) => it,
},
```

The formatter in this case is just an identity function (returns the passed in value, without any quotes), but you could do more advanced stuff like use an actual `Date` or `CalendarDate` object in the `val` instead.

**Comment by robbiefryers** [comment]
Nice, thanks a lot!

**Comment by robbiefryers** [comment]
Nice, thanks a lot!
