### ISSUE TITLE
oAuth not working

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/ts-force#17]
I fixed a couple bugs but I'm still getting invalid grant... Not sure whats going on... Maybe `axios` is adding some headers. Saleforce is super picky when it comes to oAuth.

**Comment by ChuckJonas** [comment]
related: https://salesforce.stackexchange.com/questions/172980/errorunsupported-grant-type-error-descriptiongrant-type-not-supported

It looks like axios might be passing the data in the header...

**Comment by ChuckJonas** [comment]
also: https://github.com/mzabriskie/axios/issues/362

**Comment by DServy** [comment]
Let me look at this, my guess is it will be an easy fix

**Comment by ChuckJonas** [comment]
yes...
Step 1: Don't forget to include security token w/ password

Turns out my previous commit was enough to fix the issue
