### ISSUE TITLE
Other SOQL operations like count?

### ISSUE THREAD

**Issue by b3ntly** [ChuckJonas/ts-force#35]
Is it possible to do other operations like count() using this library?

**Comment by ChuckJonas** [comment]
Sure, you can run any SOQL query and get the results like this:

```
import { Rest } from "ts-force";

const sfdcClient = Rest.Instance;
let results = await sfdcClient.query('SELECT Count(Id) FROM Account');
console.log(results);
```

**Comment by b3ntly** [comment]
Awesome! Thank's so much. Great library.

**Comment by ChuckJonas** [comment]
@b3ntly thanks!  I think it has a TON of potential.  It's still very much in it's infancy, but I've been using it in a client project for the past 6 months and I've actually been pleasantly surprised with how stable it's been.

I have a lot of 2.0 features & refactors I want to add if I ever find the time.
