### ISSUE TITLE
Bug: Circular Data Model Breaks Model Imports

### ISSUE THREAD

**Issue by ralphcallaway** [ChuckJonas/ts-force#44]
Given a circular data model
- Account 
  - Practice Lead -> Contact
- Contact 
  - Account -> Account

And I do this import
`import { Contact, FreshbooksTimeEntry } from './generated/sobs'`

I get the following error

> /Users/ralphcallaway/Documents/eclipse 3.7/dapulse/src/generated/sobs.ts:239
>     public practiceLead: Contact;
>                          ^
> ReferenceError: Contact is not defined
>     at Object.<anonymous> (/Users/ralphcallaway/Documents/eclipse 3.7/dapulse/src/generated/sobs.ts:239:26)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Module.m._compile (/Users/ralphcallaway/Documents/eclipse 3.7/dapulse/node_modules/ts-node/src/index.ts:430:23)
>     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Object.require.extensions.(anonymous function) [as .ts] (/Users/ralphcallaway/Documents/eclipse 3.7/dapulse/node_modules/ts-node/src/index.ts:433:12)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> 

Looks like the Contact class is loaded before the Account class and getting an error, reversing the order doesn't help since the Account also has a reference in that direction.

**Comment by ChuckJonas** [comment]
@ralphcallaway

What version of typescript are you running?

Also, post can you post your `tsconfig.json`?  

Circular references should work, as long as they are made in the same file (why we can't break out code generation into different files).

**Comment by ralphcallaway** [comment]
`"typescript": "^2.9.1"` (from package.json)

my `tsconfig.json`
```{
    "compilerOptions": {
        "baseUrl": "./", // enables relative imports to root
        "paths": {
            "@src/*": [
                "src/*"
            ]
        },
        "outDir": "./build",
        "target": "es6",
        "lib": [
            "es6",
            "dom"
        ],
        "module": "commonjs",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitAny": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": false,
        "noResolve": false,
        "noUnusedParameters": false,
        "noUnusedLocals": false,
        "strictNullChecks": false,
        "strict": true,
        "allowSyntheticDefaultImports": true
    },
    "include": [
        "src/**/*",
        "test/**/*.spec.ts"
    ],
    "exclude": [
        "node_modules",
        "dist"
    ]
}```

**Comment by ChuckJonas** [comment]
Having `"emitDecoratorMetadata": true,` causes this issue for some reason
