### ISSUE TITLE
Streaming API Support

### ISSUE THREAD

**Issue by dcurletti** [ChuckJonas/ts-force#53]
Is adding support for the streaming api on the roadmap?

**Comment by ChuckJonas** [comment]
basic support could be added very easy... any opinions on how it should operate or the API?

**Comment by ChuckJonas** [comment]
Just pushed a first pass...

Here's what the usage looks like at the moment:

```
// callback when we get an event
const handleNewAccount = (e: StreamingEvent) => {
  //do stuff with the stream event... In this case get the object
  const acc = new Account({ id: e.sobject.Id });
  acc.refresh().then(()=> {
    //do stuff with full account
  });
}

//setup stream listener
const stream = new SObjectStream();
let streamConn = stream.listen({
  topic: 'MyTopic',
  handler: handleNewAccount,
});

//... when your done
streamConn.disconnect(()=> console.log('disconneted'));
``

**Comment by dcurletti** [comment]
hey @ChuckJonas - not at the moment.  Might be integrating this package in the coming weeks and will have more opinions then. 

Appreciate the response!

**Comment by ChuckJonas** [comment]
I've been chipping away at this.  Turns out it wasn't as easy as I first envisioned 😁 

However, I should have a release out soon which will support both steaming api & platform events on both nodejs & in the browser.

**Comment by ChuckJonas** [comment]
you can test the new functionality out by  targeting `ts-force@2.4.0-rc9`.

Tip: Add `PushTopic` to your ts-force-config.json `SObject` and then you can do something like this:

```typescript
import { Account, PushTopic } from './generated/sobs';
import { DEFAULT_CONFIG, Streaming, buildQuery } from 'ts-force';

let TEST_ACC_NAME = 'abc-123';
topic = new PushTopic({
    name: topicName,
    notifyForOperationCreate: true,
    description: 'for unit test',
    apiVersion: DEFAULT_CONFIG.version,
    query: buildQuery(Account, f => (
        {
            select: [
                ...f.select('id', 'name', 'active')
            ],
            where: [{ field: f.select('name'), val: TEST_ACC_NAME }]
        }
    ))
});
await topic.insert();

let stream = new Streaming('node');
await stream.connect();

await stream.subscribeToTopicMapped(
    Account,
    topic.name,
    e => { //onEvent callback
        let acc: Account = e.data.sObject.name;
        console.log(acc);
    }
);

let acc = new Account({ name: TEST_ACC_NAME });
await acc.insert();
```

**Comment by ChuckJonas** [comment]
signatures and names still may change a bit but I think this is the overall functionality that will be release in v1

**Comment by ChuckJonas** [comment]
added in 2.4.2.

See https://github.com/ChuckJonas/ts-force/wiki/Streaming-&-Platform-events for documentation
