### ISSUE TITLE
refactor generator to use the @salesforce/core instead of executing sfdx-cli

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/ts-force#56]
Seems to be faster and not dependent on having the CLI installed

[@salesforce/core](https://www.npmjs.com/package/@salesforce/core)

Should just be something like this:
```typescript
const connection: Connection = await Connection.create({
      authInfo: await AuthInfo.create({ username: testData.username })
});
```

**Comment by CarsonF** [comment]
Does `ts-force` use `axios` to try and prevent using `@salesforce/core` in the browser?
Is it a goal to make this package browser compatible?

**Comment by ChuckJonas** [comment]
ya, `ts-force` needs to remain isomorphic.  I primary use it in browser applications at the moment.

Is issue is in regards to how the generator connects with salesforce.   One of the options is to use the sfdx connections.  Right now, I believe it's spawning processes that just call into the CLI (EG `sfdx force:org:display -u my-user --json`)
