### ISSUE TITLE
Support only interfaces?

### ISSUE THREAD

**Issue by JoelBrenstrum** [ChuckJonas/ts-force#63]
I would like to generate sObject types and their relationships as only interfaces without all the additional RestAPI logic.

```
export interface Account {
   Id:string,
   Name:String,
   Contacts:Array<Contact>
}

export interface Contact {
   Id:string,
   Name:String
} 
```
Is this possible? 

Thanks

**Comment by ChuckJonas** [comment]
Without name remapping (EG: `My_Custom_Field__c` -> `myCustomField`)?

It would be pretty trivial and I think there is already another project out there that maybe does this?  I recall someone building a sfdx-cli plugin for this.

I've thought about splitting away the generated mapped classes away from the RestAPI functionality, but at this point I have no immediately plans to do so.

**Comment by JoelBrenstrum** [comment]
I found https://github.com/amphro/salesforce-to-types
With some small tweaks I have got it working mostly for what I need.

https://github.com/JoelBrenstrum/salesforce-to-types

Thanks for the quick response.

**Comment by JoelBrenstrum** [comment]
I found https://github.com/amphro/salesforce-to-types
With some small tweaks I have got it working mostly for what I need.

https://github.com/JoelBrenstrum/salesforce-to-types

Thanks for the quick response.
