### ISSUE TITLE
Using the includes query operator does not wrap the value in parenthesis

### ISSUE THREAD

**Issue by ScottMGerstl** [ChuckJonas/ts-force#65]
Expected: 
`Select Id From User Where Groups__c includes ('Basic')`

Actual:
`Select Id From User Where Groups__c includes 'Basic'`

**Comment by ChuckJonas** [comment]
Ya, it looks like the type is incorrect.  I'll push a fix.  Functionality it does work if you pass an array:

https://stackblitz.com/edit/ts-force-query-playground-repo

**Comment by ChuckJonas** [comment]
fixed in 2.6.1
