### ISSUE TITLE
Config to remove namespace from mapping

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/ts-force#66]
Right now if you have a namespaced object, you'll probably end up with something like this:

```json
  "sObjects": [
    {
      "apiName": "VARS__ENV__mdt",
      "fieldMappings": [
        {"apiName": "VARS__Datatype__c", "propName": "datatype"},
        {"apiName": "VARS__Group__c", "propName": "group"},
        {"apiName": "VARS__Notes__c", "propName": "notes"},
        {"apiName": "VARS__Val__c", "propName": "val"},
        {"apiName": "VARS__Value__c", "propName": "value"},
        {"apiName": "VARS__Secret__c", "propName": "secret"}
      ],
      "className": "EnvVarRecord"
    }
```

would be much nicer to just be able to do something like this:

```
"sObjects": [
    {
      "apiName": "VARS__ENV__mdt",
      "removeNamespace": "VARS"
    }
```

and it would automatically clear the namespace from object generation .  Potential object conflicts could still be managed via a `className` attrb

**Comment by CarsonF** [comment]
Hmm I don't want to have to specify this for every object. Could there be a global flag to default it? Otherwise I could procedurally generate the config on my end.

**Comment by ChuckJonas** [comment]
Good point,  it could be both global and overriden at the object level (similar to the picklist control)

On that note, maybe it's just removes them by default?  

Then the user can turn it back on if there are actually namespace conflicts

**Comment by CarsonF** [comment]
That sounds great to me
