### ISSUE TITLE
TS Strict Mode Compatibility

### ISSUE THREAD

**Issue by CarsonF** [ChuckJonas/ts-force#81]
Currently there are two places where strict mode (strict nulls) isn't compatible with the generated classes.

## `sField` `reference`

First place is the `reference`s are sometimes undefined.
![Screen Shot 2020-02-13 at 11 08 51 AM](https://user-images.githubusercontent.com/932566/74459682-5db9da00-4e51-11ea-969d-ebaaed0513cc.png)
I'm not sure what the best solution is here. Maybe make that property nullable?
That actually seems to make sense, since non-relationship properties will not have references.

## Property Initial Values

The second place is assigning undefined to all properties in the constructor.
![Screen Shot 2020-02-13 at 11 12 45 AM](https://user-images.githubusercontent.com/932566/74459972-c99c4280-4e51-11ea-9454-442a86086126.png)
Is there an actual need for that? Maybe technically all these properties should be defined as nullable...

**Comment by ChuckJonas** [comment]
yea, I think you are right.  Before 3.0, the relationships would actually always get an empty `[]` or empty object, even if they weren't queried.  

That has since been fixed, but since it's not typed as nullable I did end up with a bunch of NPE when I upgraded my project because referencing without checking for null.


This will really help identify bugs when upgrading to 3.0

**Comment by CarsonF** [comment]
Null-coalescing operator should help ease the burden of everything being nullable.

I usually try to keep array properties non-nullable by declaring with a default value
```ts
prop: Foo[] = []
```
However, in this case making those nullable as well could help with the distinction between querying for that field and the result actually being empty vs not querying for it in which case there should be items in the array but it will be empty.

**Comment by ChuckJonas** [comment]
ya, that was my thoughts exactly.

an empty array indicates that we queried the data but there were no results.  A null array indicates that we didn't actually query the relationship.
