### ISSUE TITLE
Are lookup fields updated using external ID at the time of update

### ISSUE THREAD

**Issue by avivek** [ChuckJonas/ts-force#88]
If a contact has a lookup field in it, let us say referring to Account, and as part of the contact update, if we have to update the lookup field, can we use the external ID field as below:

let contactObj = new Contact({id:sampleId});
contactObj.refresh();
contactObj.accountrelationship = new Account({extId:sampleEXTID})
contactObj.update();

The account lookup field is still pointing to the older field.

This works at the time of insert.

**Comment by ChuckJonas** [comment]
@avivek yes, it should, but `accountRelationshipId` field will take precedence if set (https://github.com/ChuckJonas/ts-force/blob/master/ts-force/src/rest/restObject.ts#L242).

If you are not seeing this behavior, try nulling the corresponding` field out

**Comment by avivek** [comment]
Yes that worked. 
Thanks a lot for the quick response.
