### ISSUE TITLE
Event and Task objects generated file is wrong

### ISSUE THREAD

**Issue by ignacio-muino** [ChuckJonas/ts-force#96]
When adding "Event" and "Task" objects to ts-force-config.json deploy breaks. Apparently the generated files for these objects are wrong and causes the deployment to fail.

Here are some screenshots on how the Event.ts file looks like:
![Event_error_1](https://user-images.githubusercontent.com/8174465/99988419-5fc1a980-2d90-11eb-9848-65078137163a.png)
![event_error_2](https://user-images.githubusercontent.com/8174465/99988426-618b6d00-2d90-11eb-9706-41cfb5a42b4e.png)
 
And the deployment error:
![Failed_deploy](https://user-images.githubusercontent.com/8174465/99988014-e1650780-2d8f-11eb-9fec-7d985abc316a.png)

My guess is the generator is having some trouble with the "WhoId" and "WhatId" fields as these are polymorphic fields.
Is there any workaround for this or am I missing anything?

**Comment by ChuckJonas** [comment]
Ah, yea there's a bug in the generation around how the polymorphic fields are handled.  A quick fix is just to add the `Name` SObject to the `ts-force-config.json` file.

```json
{
  "$schema": "https://raw.githubusercontent.com/ChuckJonas/ts-force/master/ts-force-gen/ts-force-config.schema.json",
  "sObjects": [
    "Task",
    "Event",
    "Name" //ADD POLYMORPHIC "NAME" sObject
  ],
  "auth": {
    "username": "charlie.jonas@ccb.com.prod"
  },
  "outPath": "./src/generated"
}
```

Also, what version are you using?

I'm about to release v3.0 which has a[ bunch of bug fixes and improvements](https://github.com/ChuckJonas/ts-force/pull/79/files?short_path=3bd14d0#diff-3bd14d078188074c410028847113ceae68865d0ad5b844a27183ef87fbe2fcc3) (with only some minor breaking changes to seldomly used features). 

I recommend upgrading to the latest release candidate if you already aren't using it.  

```
npm install ts-force@3.0.0-rc.20
npm install -D ts-force-gen@3.0.0-rc.20
```

**Comment by ignacio-muino** [comment]
Thank you so much for the quick answer. Timing for 3.0r.c can't be better 😄  So far it fixed my issues and everything else seems to be working as expected. I'll let you know if I find any other issue while using it.
Since 3.0 is a release candidate and solves the issues described above, I think I can close this issue now.
