### ISSUE TITLE
Why use old version of cometd client?

### ISSUE THREAD

**Issue by calvinwyoung** [ChuckJonas/ts-force#97]
I noticed that the `cometd` client was pinned to an older version (v4.0.3) in [this release](https://github.com/ChuckJonas/ts-force/commit/85c33a03d107671f66fd4c954e4367f901d96db3), but the current version `cometd` is at v5.0.2.

Out of curiosity, do you remember why you had to do this?

**Comment by calvinwyoung** [comment]
Closing this issue — realized this was caused by a `cometd-nodejs-client` issue:
https://github.com/cometd/cometd-nodejs-client/issues/18

**Comment by ChuckJonas** [comment]
@calvinwyoung  You might checkout https://www.npmjs.com/package/@salesforce/bunyan.  It's what they use in the CLI

**Comment by calvinwyoung** [comment]
@ChuckJonas Makes sense, thanks for the pointer. Why did you choose to use the `cometd` client instead of `faye`? It seems like `faye` ought to be preferable since it doesn't monkeypatch the global `window` object.

**Comment by ChuckJonas** [comment]
@calvinwyoung  I tried it, but believe I ran into issues with the API not being very compatible with what I was trying to do.  I can't recall exactly.   

Also, back when I implemented streaming, the "official salesforce docs" pointed to `cometd`.

Let me know how it goes and maybe I'll upgrade (although probably not without good reason.  Faye is 5x larger and has a big dependency chain)
